export const types = {
    //Sync
    FETCH_POSTS:  'FETCH_POSTS',
    VIEW_POST:    'VIEW_POST',
    VIEW_COMMENT: 'VIEW_COMMENT',

    //Async
    FETCH_POSTS_ASYNC:  'FETCH_POSTS_ASYNC',
    VIEW_POST_ASYNC:    'VIEW_POST_ASYNC',
    VIEW_COMMENT_ASYNC: 'VIEW_COMMENT_ASYNC',
};
